export const GET_TEAM = "GET_TEAM";
export const GET_TEAM_ERROR = "GET_TEAM_ERROR";

export const GET_MEMBER_DETAILS = "GET_MEMBER_DETAILS";
export const GET_MEMBER_DETAILS_ERROR = "GET_MEMBER_DETAILS_ERROR";

export const ADD_MEMBER = "ADD_MEMBER";
export const ADD_MEMBER_ERROR = "ADD_MEMBER_ERROR";

export const UPDATE_MEMBER = "UPDATE_MEMBER";
export const UPDATE_MEMBER_ERROR = "UPDATE_MEMBER_ERROR";

export const DELETE_MEMBER = "DELETE_MEMBER";
export const DELETE_MEMBER_ERROR = "DELETE_MEMBER_ERROR";